apiVersion: v1
kind: Namespace
metadata:
  name: automatch

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: automatch-nventory-script-configmap
  namespace: automatch
data:
  NODE_ENV: "staging"
  NEOAUTO_URL: "https://neoauto.com"
  MERCADOLIBRE_URL: "https://listado.mercadolibre.com.pe"
  AUTOCOSMOS_URL: "https://autocosmos.com.pe"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: automatch-nventory-script-job
  namespace: automatch
spec:
  schedule: "0 */8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: automatch-script-job
        spec:
          containers:
          - name: ms-automatch-jobs
            image: 020503494232.dkr.ecr.us-east-1.amazonaws.com/ms-automatch-jobs-image:1.1
            env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: automatch-script-configmap
                  key: NODE_ENV
            - name: NEOAUTO_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-script-configmap
                  key: NEOAUTO_URL
            - name: MERCADOLIBRE_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-script-configmap
                  key: MERCADOLIBRE_URL
            - name: AUTOCOSMOS_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-script-configmap
                  key: AUTOCOSMOS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: automatch-script-secret
                  key: database
            - name: BETTERSTACK_LOGTAIL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: automatch-script-secret
                  key: logtailtoken
          restartPolicy: OnFailure