apiVersion: v1
kind: ConfigMap
metadata:
  name: automatch-configmap
  namespace: automatch-cluster
data:
  NODE_ENV: "staging"
  NEOAUTO_URL: "https://neoauto.com"
  MERCADOLIBRE_URL: "https://listado.mercadolibre.com.pe"
  AUTOCOSMOS_URL: "https://autocosmos.com.pe"

