apiVersion: v1
kind: Namespace
metadata:
  name: automatch

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: automatch-inventory-script-configmap
  namespace: automatch
data:
  NODE_ENV: "production"
  DATABASE_URL: "mongodb+srv://victbenavente:023FjoIZxpOQFKEa@automatch-mongo-cluster.tjppmyq.mongodb.net/automatch-inventory?retryWrites=true&w=majority"
  FOREX_API_URL: "https://api.polygon.io/v2"
  FOREX_API_KEY: "26GqXsECtWlFRBHMLr6uptVocAMfemr1"
  BETTERSTACK_LOGTAIL_TOKEN: "ikSrYrVgChAyVnAjDt4FYfH3"
  NEOAUTO_URL: "https://neoauto.com"
  MERCADOLIBRE_URL: "https://listado.mercadolibre.com.pe"
  AUTOCOSMOS_URL: "https://autocosmos.com.pe"
  AUTOPIA_URL: "https://autopia.pe"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: automatch-inventory-script-cronjob
  namespace: automatch
spec:
  schedule: "0 */4 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: automatch-inventory-script-cronjob
        spec:
          containers:
          - name: automatch-inventory-script
            image: victor0141/automatch-inventory-script:1.1
            restartPolicy: OnFailure
            env:
              - name: NODE_ENV
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: NODE_ENV
              - name: DATABASE_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: DATABASE_URL
              - name: FOREX_API_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: FOREX_API_URL
              - name: FOREX_API_KEY
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: FOREX_API_KEY
              - name: BETTERSTACK_LOGTAIL_TOKEN
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: BETTERSTACK_LOGTAIL_TOKEN
              - name: NEOAUTO_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: NEOAUTO_URL
              - name: MERCADOLIBRE_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: MERCADOLIBRE_URL
              - name: AUTOCOSMOS_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: AUTOCOSMOS_URL
              - name: AUTOPIA_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-script-configmap
                    key: AUTOPIA_URL