apiVersion: batch/v1
kind: CronJob
metadata:
  name: automatch-inventory-script-cronjob
  namespace: automatch
spec:
  schedule: "0 */8 * * *"
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: automatch-inventory-script-cronjob
        spec:
          restartPolicy: Never
          containers:
          - name: automatch-inventory-script
            image: victor0141/automatch-inventory-script:1.2
            env:
              - name: NODE_ENV
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: NODE_ENV
              - name: DATABASE_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: DATABASE_URL
              - name: FOREX_API_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: FOREX_API_URL
              - name: FOREX_API_KEY
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: FOREX_API_KEY
              - name: BETTERSTACK_LOGTAIL_TOKEN
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: BETTERSTACK_LOGTAIL_TOKEN
              - name: NEOAUTO_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: NEOAUTO_URL
              - name: MERCADOLIBRE_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: MERCADOLIBRE_URL
              - name: AUTOCOSMOS_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: AUTOCOSMOS_URL
              - name: AUTOPIA_URL
                valueFrom:
                  configMapKeyRef:
                    name: automatch-inventory-script-configmap
                    key: AUTOPIA_URL