apiVersion: batch/v1
kind: Job
metadata:
  name: automatch-job
  namespace: automatch-cluster
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 3600
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: ms-vmotor-job
          image: victor0141/ms-vmotor-jobs:1.4
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: automatch-configmap
                  key: NODE_ENV
            - name: NEOAUTO_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-configmap
                  key: NEOAUTO_URL
            - name: MERCADOLIBRE_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-configmap
                  key: MERCADOLIBRE_URL
            - name: AUTOCOSMOS_URL
              valueFrom:
                configMapKeyRef:
                  name: automatch-configmap
                  key: AUTOCOSMOS_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: automatch-secrets
                  key: database
            - name: BETTERSTACK_LOGTAIL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: automatch-secrets
                  key: logtailtoken
